### ISSUE TITLE
勝敗が決した後の再戦機能がほしい

### ISSUE THREAD

**Issue by eijiszk** [kokoroszk/avalon-back#3]
同じメンバーで続けてプレイを行うため
勝敗が決した後にルームを再作成するのではなく、再戦する機能がほしい

**Comment by kokoroszk** [comment]
@eijiszk 
指定したIDのゲームを初期化するIF作りました。
呼び出せるようにフロントを修正する必要あります。

**Comment by kokoroszk** [comment]
https://github.com/kokoroszk/avalon-back/pull/5

**Comment by kokoroszk** [comment]
マージされたのでクローズします。
